/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universityManagement;

import java.io.FileNotFoundException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author MD SHAHIN KAMAL
 */
public class Project extends javax.swing.JFrame {

    /**
     * Creates new form Project
     */
    public Project() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Facul = new javax.swing.JButton();
        HeadNmae = new javax.swing.JTextField();
        Head = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        FM1 = new javax.swing.JTextField();
        FM3 = new javax.swing.JTextField();
        FM2 = new javax.swing.JTextField();
        FM5 = new javax.swing.JTextField();
        Depart = new javax.swing.JButton();
        TextField11 = new javax.swing.JTextField();
        TextField12 = new javax.swing.JTextField();
        TextField13 = new javax.swing.JTextField();
        TextField14 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Semester = new javax.swing.JComboBox<>();
        IDBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        IDInput = new javax.swing.JLabel();
        Sub = new javax.swing.JButton();
        result = new javax.swing.JTextField();
        DepatCombo = new javax.swing.JComboBox<>();
        Click = new javax.swing.JButton();
        FMCOMBO = new javax.swing.JComboBox<>();
        FMCLICK = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Button2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        shahin = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(51, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("         University Management System");
        jLabel1.setAutoscrolls(true);
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 2, 3, 2, new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(27, 31, 551, 46);

        Facul.setBackground(new java.awt.Color(255, 255, 255));
        Facul.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 18)); // NOI18N
        Facul.setText("Faculty Member");
        Facul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FaculActionPerformed(evt);
            }
        });
        getContentPane().add(Facul);
        Facul.setBounds(10, 90, 230, 50);
        getContentPane().add(HeadNmae);
        HeadNmae.setBounds(27, 265, 134, 20);

        Head.setBackground(new java.awt.Color(0, 0, 0));
        Head.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Head.setForeground(new java.awt.Color(255, 51, 51));
        Head.setText("Head of SWE");
        getContentPane().add(Head);
        Head.setBounds(27, 230, 117, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Faculty Member");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(27, 291, 107, 17);

        FM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FM1ActionPerformed(evt);
            }
        });
        getContentPane().add(FM1);
        FM1.setBounds(27, 319, 134, 20);

        FM3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FM3ActionPerformed(evt);
            }
        });
        getContentPane().add(FM3);
        FM3.setBounds(27, 386, 134, 20);
        getContentPane().add(FM2);
        FM2.setBounds(27, 355, 134, 20);

        FM5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FM5ActionPerformed(evt);
            }
        });
        getContentPane().add(FM5);
        FM5.setBounds(27, 424, 134, 20);

        Depart.setBackground(new java.awt.Color(255, 255, 255));
        Depart.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        Depart.setText("Department");
        Depart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepartActionPerformed(evt);
            }
        });
        getContentPane().add(Depart);
        Depart.setBounds(240, 90, 170, 50);
        getContentPane().add(TextField11);
        TextField11.setBounds(240, 410, 165, 20);
        getContentPane().add(TextField12);
        TextField12.setBounds(240, 280, 165, 20);
        getContentPane().add(TextField13);
        TextField13.setBounds(240, 320, 165, 20);
        getContentPane().add(TextField14);
        TextField14.setBounds(240, 360, 165, 20);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Rockwell Condensed", 1, 24)); // NOI18N
        jButton1.setText("CGPA");
        getContentPane().add(jButton1);
        jButton1.setBounds(410, 90, 180, 50);

        Semester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Spring 15", "Summer 15", "Fall 15", "Spring 16" }));
        getContentPane().add(Semester);
        Semester.setBounds(410, 210, 157, 20);

        IDBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "151-35-901", "151-35-902", "151-35-903", "151-35-904", "151-35-905", "151-35-906", "151-35-907", "151-35-908" }));
        getContentPane().add(IDBox);
        IDBox.setBounds(410, 280, 157, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Select Semester");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(410, 140, 157, 31);

        IDInput.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        IDInput.setForeground(new java.awt.Color(255, 51, 51));
        IDInput.setText("Enter Your ID");
        getContentPane().add(IDInput);
        IDInput.setBounds(410, 250, 157, 17);

        Sub.setText("Submit");
        Sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubActionPerformed(evt);
            }
        });
        getContentPane().add(Sub);
        Sub.setBounds(410, 320, 100, 23);
        getContentPane().add(result);
        result.setBounds(410, 360, 157, 20);

        DepatCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Faculty of FIST", "Faculty of FIHS", "Faculty of FBE", "Faculty of AHCH" }));
        getContentPane().add(DepatCombo);
        DepatCombo.setBounds(240, 150, 165, 20);

        Click.setText("Click me");
        Click.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClickActionPerformed(evt);
            }
        });
        getContentPane().add(Click);
        Click.setBounds(240, 210, 165, 23);

        FMCOMBO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SWE", "CSE", "ETE", "EEE" }));
        FMCOMBO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FMCOMBOActionPerformed(evt);
            }
        });
        getContentPane().add(FMCOMBO);
        FMCOMBO.setBounds(30, 150, 134, 20);

        FMCLICK.setText("Click Me");
        FMCLICK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FMCLICKActionPerformed(evt);
            }
        });
        getContentPane().add(FMCLICK);
        FMCLICK.setBounds(27, 196, 134, 23);

        jLabel3.setMaximumSize(new java.awt.Dimension(1300, 600));
        jLabel3.setMinimumSize(new java.awt.Dimension(1300, 600));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 590, 470);

        Button2.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        Button2.setText("ABOUT ");
        Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button2ActionPerformed(evt);
            }
        });
        getContentPane().add(Button2);
        Button2.setBounds(130, 480, 320, 60);

        shahin.setColumns(20);
        shahin.setRows(5);
        jScrollPane1.setViewportView(shahin);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(6, 550, 610, 240);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FaculActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FaculActionPerformed
          
        
        
        
      
        
       
        
      
        
        
        
    }//GEN-LAST:event_FaculActionPerformed

    private void FM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FM1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FM1ActionPerformed

    private void FM5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FM5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FM5ActionPerformed

    private void DepartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepartActionPerformed
        // TODO add your handling code here:
        
        
        
        
        
        
         
        
    }//GEN-LAST:event_DepartActionPerformed

    private void SubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubActionPerformed
        // TODO add your handling code here:
        
         if(Semester.getSelectedItem().equals("Spring 15") && IDBox.getSelectedItem().equals("151-35-901")){
            
             result.setText("Result is 3.08");            
        }
         else  if(Semester.getSelectedItem().equals("Summer 15") && IDBox.getSelectedItem().equals("151-35-901")){
            
             result.setText("Result is 3.15");            
        }
         
  else  if(Semester.getSelectedItem().equals("Fall 15") && IDBox.getSelectedItem().equals("151-35-901")){
            
             result.setText("Result is 3.13");            
        }
         else  if(Semester.getSelectedItem().equals("Spring 16") && IDBox.getSelectedItem().equals("151-35-901")){
            
             result.setText("Result is 3.25");            
        }
         
         else if(Semester.getSelectedItem().equals("Spring 15") && IDBox.getSelectedItem().equals("151-35-902")){
            
             result.setText("Result is 3.28");            
        }
         else  if(Semester.getSelectedItem().equals("Summer 15") && IDBox.getSelectedItem().equals("151-35-902")){
            
             result.setText("Result is 3.25");            
        }
         
          else  if(Semester.getSelectedItem().equals("Fall 15") && IDBox.getSelectedItem().equals("151-35-902")){
            
             result.setText("Result is 3.23");            
        }
         else  if(Semester.getSelectedItem().equals("Spring 16") && IDBox.getSelectedItem().equals("151-35-902")){
            
             result.setText("Result is 4.00");            
        }
        else   if(Semester.getSelectedItem().equals("Spring 15") && IDBox.getSelectedItem().equals("151-35-903")){
            
             result.setText("Result is 3.88");            
        }
         else  if(Semester.getSelectedItem().equals("Summer 15") && IDBox.getSelectedItem().equals("151-35-903")){
            
             result.setText("Result is 3.95");            
        }
         
          else  if(Semester.getSelectedItem().equals("Fall 15") && IDBox.getSelectedItem().equals("151-35-903")){
            
             result.setText("Result is 3.53");            
        }
         else  if(Semester.getSelectedItem().equals("Spring 16") && IDBox.getSelectedItem().equals("151-35-903")){
            
             result.setText("Result is 3.65");            
        }
           else  if(Semester.getSelectedItem().equals("Spring 15") && IDBox.getSelectedItem().equals("151-35-904")){
            
             result.setText("Result is 3.78");            
        }
         else  if(Semester.getSelectedItem().equals("Summer 15") && IDBox.getSelectedItem().equals("151-35-904")){
            
             result.setText("Result is 3.55");            
        }
         
          else  if(Semester.getSelectedItem().equals("Fall 15") && IDBox.getSelectedItem().equals("151-35-904")){
            
             result.setText("Result is 3.23");            
        }
         else  if(Semester.getSelectedItem().equals("Spring 16") && IDBox.getSelectedItem().equals("151-35-904")){
            
             result.setText("Result is 3.34");  
         }   
            else   if(Semester.getSelectedItem().equals("Spring 15") && IDBox.getSelectedItem().equals("151-35-905")){
            
             result.setText("Result is 3.28");            
        }
         else  if(Semester.getSelectedItem().equals("Summer 15") && IDBox.getSelectedItem().equals("151-35-905")){
            
             result.setText("Result is 3.45");            
        }
         
          else  if(Semester.getSelectedItem().equals("Fall 15") && IDBox.getSelectedItem().equals("151-35-905")){
            
             result.setText("Result is 3.43");            
        }
         else  if(Semester.getSelectedItem().equals("Spring 16") && IDBox.getSelectedItem().equals("151-35-905")){
            
             result.setText("Result is 3.75");            
        }
         
         else   if(Semester.getSelectedItem().equals("Spring 15") && IDBox.getSelectedItem().equals("151-35-906")){
            
             result.setText("Result is 3.78");            
        }
         else  if(Semester.getSelectedItem().equals("Summer 15") && IDBox.getSelectedItem().equals("151-35-906")){
            
             result.setText("Result is 3.15");            
        }
         
          else  if(Semester.getSelectedItem().equals("Fall 15") && IDBox.getSelectedItem().equals("151-35-906")){
            
             result.setText("Result is 2.43");            
        }
         else  if(Semester.getSelectedItem().equals("Spring 16") && IDBox.getSelectedItem().equals("151-35-906")){
            
             result.setText("Result is 2.75");            
        }
         
         else   if(Semester.getSelectedItem().equals("Spring 15") && IDBox.getSelectedItem().equals("151-35-907")){
            
             result.setText("Result is 3.78");            
        }
         else  if(Semester.getSelectedItem().equals("Summer 15") && IDBox.getSelectedItem().equals("151-35-907")){
            
             result.setText("Result is 1.45");            
        }
         
          else  if(Semester.getSelectedItem().equals("Fall 15") && IDBox.getSelectedItem().equals("151-35-907")){
            
             result.setText("Result is 3.67");            
        }
         else  if(Semester.getSelectedItem().equals("Spring 16") && IDBox.getSelectedItem().equals("151-35-907")){
            
             result.setText("Result is 3.75");   
             
        }
        
         
         else   if(Semester.getSelectedItem().equals("Spring 15") && IDBox.getSelectedItem().equals("151-35-908")){
            
             result.setText("Result is 3.18");            
        }
         else  if(Semester.getSelectedItem().equals("Summer 15") && IDBox.getSelectedItem().equals("151-35-908")){
            
             result.setText("Result is 3.45");            
        }
         
          else  if(Semester.getSelectedItem().equals("Fall 15") && IDBox.getSelectedItem().equals("151-35-908")){
            
             result.setText("Result is 3.43");            
        }
         else  if(Semester.getSelectedItem().equals("Spring 16") && IDBox.getSelectedItem().equals("151-35-908")){
            
             result.setText("Result is 3.33");            
        }
    }//GEN-LAST:event_SubActionPerformed

    private void ClickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClickActionPerformed
        
         if(DepatCombo.getSelectedItem().equals("Faculty of FIST")){
            
                String resul91 ="\n" ;
          TextField11.setText("            CSE "+resul91);
          
          String resul92 ="\n" ;
          TextField12.setText("            SWE "+resul92);
          
          String resul93 ="\n" ;
          TextField13.setText("            EEE "+resul93);
          
          String resul94 ="\n" ;
          TextField14.setText("            ETE "+resul94);
                 
        }
         
         else 
         if(DepatCombo.getSelectedItem().equals("Faculty of FIHS")){
            
                String resul91 ="\n" ;
          TextField11.setText("     Journalism "+resul91);
          
                       String resul92 ="\n" ;
          TextField12.setText("       Law "+resul92);
          
          String resul93 ="\n" ;
          TextField13.setText("        Enlish "+resul93);
          
           String resul94 ="\n" ;
          TextField14.setText("       Bangla    "+resul93);
         
                 
        }
       else  if(DepatCombo.getSelectedItem().equals("Faculty of FBE")){
            
                String resul91 ="\n" ;
          TextField11.setText("     Business Administration"+resul91);
          
          String resul92 ="\n" ;
          TextField12.setText("    Real Estate "+resul92);
          
          String resul93 ="\n" ;
          TextField13.setText("Tourism & Hospitality Management"+resul93);
          
          String resul94 ="\n" ;
          TextField14.setText("         Commerce "+resul94);
                 
        }
          else  if(DepatCombo.getSelectedItem().equals("Faculty of AHCH")){
            
                String resul91 ="\n" ;
          TextField11.setText("    Pharmacy"+resul91);
          
          String resul92 ="\n" ;
          TextField12.setText("    Public Health "+resul92);
          
          String resul93 ="\n" ;
          TextField13.setText("Nutrition & Food Engineering"+resul93);
          
          String resul94 ="\n" ;
          TextField14.setText("       Life Science "+resul94);
                 
        }
        
    }//GEN-LAST:event_ClickActionPerformed

    private void FM3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FM3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FM3ActionPerformed

    private void FMCLICKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FMCLICKActionPerformed
        
        if(FMCOMBO.getSelectedItem().equals("SWE")){
            HeadNmae.setText("   Mr. Touhid Bhuiyan");
        
        
          
           
                
          FM1.setText("Farjana Sadia");
                
               
              
        
            FM2.setText("     Mukul hossain ");
              
       
            FM3.setText("     Solaiman ");
              
        
            FM5.setText("     Md Shamim Reza ");
              
        
      
        }
         else if(FMCOMBO.getSelectedItem().equals("CSE")){
            HeadNmae.setText("   Dr.YOUSUF ALI");
        
     
            FM1.setText("     mahafuzur ");
       
            FM2.setText("     Mizanur rahman ");
              
      
            FM3.setText("     Ovi ");
              
       
            FM5.setText("     Md Shahin Kamal ");
              
         }
        
          else if(FMCOMBO.getSelectedItem().equals("ETE")){
            HeadNmae.setText("  MIzan");
        
     
            FM1.setText("   Masruma Khatun ");
       
            FM2.setText("   Sultana Ayesha  ");
              
      
            FM3.setText("     Md Shahin ");
              
       
            FM5.setText("     Md Shamim ");
              
         }
          else if(FMCOMBO.getSelectedItem().equals("EEE")){
      
        HeadNmae.setText("    Taifur Rahman");
        
     
            FM1.setText("      Monirul Islam   ");
       
            FM2.setText("     Shoriful Islam ");
              
      
            FM3.setText("     Shohidul Islam ");
              
       
            FM5.setText("     Mizanur Rahman ");
              
         }
    }//GEN-LAST:event_FMCLICKActionPerformed

    private void FMCOMBOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FMCOMBOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FMCOMBOActionPerformed

    private void Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button2ActionPerformed
        // TODO add your handling code here:
       
        
        
        java.io.File file=new java.io.File("about.txt");
        
                            try{
                                Scanner input=new Scanner(file);
                                String num="";
                                while(input.hasNext()){
                                     num+=input.nextLine()+"\n";
                                     shahin.setText(num);
                                }

                            } catch (Exception ex) {
                                JOptionPane.showMessageDialog(null, "File not Found");
                            }  
        
        
    }//GEN-LAST:event_Button2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Project().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button2;
    private javax.swing.JButton Click;
    private javax.swing.JButton Depart;
    private javax.swing.JComboBox<String> DepatCombo;
    private javax.swing.JTextField FM1;
    private javax.swing.JTextField FM2;
    private javax.swing.JTextField FM3;
    private javax.swing.JTextField FM5;
    private javax.swing.JButton FMCLICK;
    private javax.swing.JComboBox<String> FMCOMBO;
    private javax.swing.JButton Facul;
    private javax.swing.JLabel Head;
    private javax.swing.JTextField HeadNmae;
    private javax.swing.JComboBox<String> IDBox;
    private javax.swing.JLabel IDInput;
    private javax.swing.JComboBox<String> Semester;
    private javax.swing.JButton Sub;
    private javax.swing.JTextField TextField11;
    private javax.swing.JTextField TextField12;
    private javax.swing.JTextField TextField13;
    private javax.swing.JTextField TextField14;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField result;
    private javax.swing.JTextArea shahin;
    // End of variables declaration//GEN-END:variables
}
